package com.ensolution.ensol.common.enums;

// ENUM('MONTHLY', 'TWICEAMONTH', 'ONCEINFEBRUARY', 'QUARTERLY', 'SEMIANNUAL', 'ANNUAL', 'ADDITIONAL', 'NOMEASURE')

public enum CycleType {
  MONTHLY,
  TWICEAMONTH,
  ONCEINFEBRUARY,
  QUARTERLY,
  SEMIANNUAL,
  ANNUAL,
  ADDITIONAL,
  NOMEASURE
}
